### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ct-hub** [JorgeFCS/Image-fusion-GAN#1]
Hello, I have some questions.
1.You train with RGB dataset and used transfer learning on fire data sets. Why not use fire data sets for training?
2.You compare three models, but two models are trained with other data sets. Is there a problem with that?
Looking forward to your reply. Thank you

**Comment by JorgeFCS** [comment]
Hi! In answer to your questions:
1.- We do this because first, we compare this model against two state-of-the-art ones. These models were originally trained on non-fire images, and we then test them on the fire dataset. To do a fair comparison with our model, we first do the same; we train it with non-fire images (the RGB-NIR dataset) and test it on the fire images. Then, to specialize it to fire images, we use transfer learning since it requires fewer training epochs and thus is faster than re-training the model from scratch on fire images.

2.- No, we only compare the three of them when they all are trained on non-fire images and tested on fire images. 

Just as a final note, the pre-trained model included in this repo is the one trained only on the non-fire images, to make it as general-purpose as possible.
